/* -*- C++ -*- */
/* Generated by opendds_idl.exe version 3.9 (ACE version 6.2a_p10) running on input file C:\OpenDDS-3.9\DevGuideExamples\DCPS\IDL\MessageOUT.idl */
#ifndef OPENDDS_IDL_GENERATED_MESSAGEOUTTYPESUPPORTIMPL_H_MFWFV0
#define OPENDDS_IDL_GENERATED_MESSAGEOUTTYPESUPPORTIMPL_H_MFWFV0
#include "MessageOUTC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DCPS/Serializer.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Messenger */



/* Begin STRUCT: MessageOUT */

namespace OpenDDS { namespace DCPS {

void gen_find_size(const Messenger::MessageOUT& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Messenger::MessageOUT& stru);

bool operator>>(Serializer& strm, Messenger::MessageOUT& stru);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Messenger::MessageOUT>();
void gen_skip_over(Serializer& ser, Messenger::MessageOUT*);

}  }

#endif

/* End STRUCT: MessageOUT */

/* End MODULE: Messenger */
#endif /* OPENDDS_IDL_GENERATED_MESSAGEOUTTYPESUPPORTIMPL_H_MFWFV0 */
