/* -*- C++ -*- */
/* Generated by opendds_idl.exe version 3.9 (ACE version 6.2a_p10) running on input file C:\OpenDDS-3.9\DevGuideExamples\DCPS\IDL\MessageIN.idl */
#ifndef OPENDDS_IDL_GENERATED_MESSAGEINTYPESUPPORTIMPL_H_B1TMPM
#define OPENDDS_IDL_GENERATED_MESSAGEINTYPESUPPORTIMPL_H_B1TMPM
#include "MessageINC.h"
#include "dds/DCPS/Definitions.h"
#include "dds/DCPS/Serializer.h"


/* Begin MODULE: CORBA */


/* End MODULE: CORBA */


/* Begin MODULE: Messenger */



/* Begin STRUCT: MessageIN */

namespace OpenDDS { namespace DCPS {

void gen_find_size(const Messenger::MessageIN& stru, size_t& size, size_t& padding);

bool operator<<(Serializer& strm, const Messenger::MessageIN& stru);

bool operator>>(Serializer& strm, Messenger::MessageIN& stru);

}  }

#ifndef OPENDDS_NO_CONTENT_SUBSCRIPTION_PROFILE
namespace OpenDDS { namespace DCPS {

class MetaStruct;

template<typename T>
const MetaStruct& getMetaStruct();

template<>
const MetaStruct& getMetaStruct<Messenger::MessageIN>();
void gen_skip_over(Serializer& ser, Messenger::MessageIN*);

}  }

#endif

/* End STRUCT: MessageIN */

/* End MODULE: Messenger */
#endif /* OPENDDS_IDL_GENERATED_MESSAGEINTYPESUPPORTIMPL_H_B1TMPM */
